### ISSUE TITLE
Logical errors in output programs

### ISSUE THREAD

**Issue by swaratchaudhuri** [capergroup/bayou#102]
On the query: 

import java.util.*;
public class TestStack {
    void foo(Stack<String> s) {
       /// calls:pop calls:isEmpty
    }
}

one of the top-3 outputs is:

import java.util.*;
public class TestStack {
    void foo(Stack<String> s) {
		String s1;
		boolean b;
		if (b = s.isEmpty()) {
			s1 = s.pop();
		} else {
		}
	}
}

This error won't show up if we treat isEmpty and !isEmpty as distinct API calls. I think we should do so, for not just isEmpty but all API calls with boolean return values.

**Comment by vijay-murali** [comment]
Added feature in pull request #124.
