### ISSUE TITLE
LLE CONFIG_INFER issue

### ISSUE THREAD

**Issue by jajajaqlt** [capergroup/bayou#111]
In lle, evidence.py, we currently have

CONFIG_INFER = ['chars', 'vocab', 'vocab_size']

    def init_config(self, evidence, chars_vocab):
        for attr in CONFIG_ENCODER + (CONFIG_INFER if chars_vocab else []):
            self.__setattr__(attr, evidence[attr])

    def dump_config(self):
        js = {attr: self.__getattribute__(attr) for attr in CONFIG_ENCODER + CONFIG_INFER}
        return js

This does not make sense since are all inside the decoder, right? And, evidence does not have those attributes. Or, in lle, evidences are supposed to have the vocabulary since it uses a bag-of-words representation? 
My config.json is this one /home/vm17/Work/bayou/trained/s3/model-10/model-10.49.tar.gz.

**Comment by jajajaqlt** [comment]
The json file is on sisyphus.

**Comment by vijay-murali** [comment]
In the LLE model evidences have those attributes since we use a sparse vector representation.

**Comment by jajajaqlt** [comment]
Yeah, I understand that. But the configuration json file does not have the vocabulary info for the evidence.

**Comment by vijay-murali** [comment]
model-10.49 is an LDA model so it doesn't need to have the vocabulary info in config.json. The LDA model is stored in the pickle file under the embed_* folders.

**Comment by jajajaqlt** [comment]
I saw it.

**Comment by vijay-murali** [comment]
If you have no further questions, can you close the issue?

**Comment by jajajaqlt** [comment]
Sure.
