### ISSUE TITLE
How can I generate the input json of "bayou/src/main/python/scripts/evidence_extractor.py"?

### ISSUE THREAD

**Issue by shelfee** [capergroup/bayou#113]
In "bayou/src/main/python/scripts/evidence_extractor.py", the Helper denotes that this script is to extract evidences from a raw data file with sequences generated by driver. Is "driver" "bayou/src/main/java/edu/rice/cs/caper/bayou/application/dom_driver/Driver.java"? But "bayou/src/main/java/edu/rice/cs/caper/bayou/application/dom_driver/Driver.java" generate jsons different from the format defined in  "bayou/src/main/python/scripts/evidence_extractor.py".
Can you explain the meaning of "keywords" in the json defined in "bayou/src/main/python/scripts/evidence_extractor.py" and how can we get the keywords?

**Comment by vijay-murali** [comment]
Yes, "driver" is the dom_driver application. It was written to extract data from a large corpus of programs, independent from the core Bayou packages, and so it's documentation is not in this repository.

To compile the driver,
```
tool_files/maven_3_3_9/dom_driver
mvn package
```
Once it has compiled, use the following command to run the driver on `Program.java` with the config file `config.json`:
```
java -jar target/dom_driver-1.0-jar-with-dependencies.jar -f Program.java -c config.json [-o output.json]
```
Run driver with -h for details about the config file. The -o option can be used to output the sketch to a JSON file.

To create a single JSON file with the entire dataset, append the JSON files from each program and create a top level JSON entity called "programs" that has the entire list as the value. For example, if you have files `Program1.json`, ... `Program10000.json` from the dataset, then the collated file should have the content:
```
{
  "programs": [
    <Program1.json>,
    <Program2.json>,
    ...
    <Program10000.json>
  ]
}
```
This can then be fed to evidence_extractor.py and other core Bayou modules.

**Comment by vijay-murali** [comment]
Keywords are obtained by chopping up the API calls and types based on camelCase. If an API call is "java.io.BufferedReader.readLine", keywords from this call would be: java io buffered reader read line. See https://github.com/capergroup/bayou/blob/master/src/main/python/bayou/core/evidence.py#L272.

**Comment by vijay-murali** [comment]
Closing this. Feel free to re-open if you have further questions.
