### ISSUE TITLE
api_calls.from_call throws error when call=CLASS0

### ISSUE THREAD

**Issue by jajajaqlt** [capergroup/bayou#114]
When I run ast_quality_perf_test, in the stack, it will run api_calls.from_call. But when the call=CLASS0, which is in the vocabulary in the config file, an error will be thrown out. Is this a bug or CLASS0 shouldn't appear. I made my fix below. It's now in the auto-validate branch.

```
     @staticmethod
      def from_call(call):
 -        split = call.split('(')[0].split('.')
 -        cls, name = split[-2:]
 -        cls = cls.split('<')[0]  # class name might be generic but method name is never
 -        return [name] if not cls == name else []
 -
 +        try:
 +		split = call.split('(')[0].split('.')
 +        	cls, name = split[-2:]
 +        	cls = cls.split('<')[0]  # class name might be generic but method name is never
 +        	return [name] if not cls == name else []
 +	except Exception as e:
 +		with open('bad_call.txt','w') as f:
 +			f.write('call: ' + call)
 +		return [call]
```

**Comment by vijay-murali** [comment]
C0 is a remnant from old code. It's not really used in the model other than being added to its vocabulary, so the model shouldn't predict it at any time (if it trained well). Which model file are you using? Are you running the bayou.core implementation?

**Comment by vijay-murali** [comment]
@jajajaqlt, as an aside, is your code in auto-validate branch ready to be merged with master? If so start a pull request and I'll attend to it.

**Comment by jajajaqlt** [comment]
@vijay-murali I have the issue with model 1,9,11 (trained on Oct. 2*). And the code I use branched 3-4 days ago from the the master. It shouldn't be too old, right? My code captured the error which was led by 'CLASS0'. This not only makes a bug in core/evidence.api_calls.from_call but also in core/evidence.types.from_call. Any more ideas? I can investigate into it more given you're quite busy now. BTW, could you direct me to our best javadoc dataset? Thanks!!

**Comment by jajajaqlt** [comment]
@vijay-murali  Thought I found something for the reason of bug. The code is attached at the bottom. If you look at these two lines.
```
            idx = np.random.choice(range(len(dist)), p=dist)
            prediction = self.model.config.decoder.chars[idx]
```
You will see any token in the chars of the decoder of the config is possible to be selected as the last DPICall `node = in_nodes[-1]` and put into calls `self.calls_in_last_ast.append(node)`. Right now, I don't think we get rid of this **CLASS0**, which is in a completely different format from other calls, in our config.

```
    def gen_until_STOP(self, psi, depth, in_nodes, in_edges, check_call=False):
        ast = []
        nodes, edges = in_nodes[:], in_edges[:]
        num = 0
        while True:
            assert num < MAX_GEN_UNTIL_STOP # exception caught in main
            dist = self.model.infer_ast(self.sess, psi, nodes, edges)
            idx = np.random.choice(range(len(dist)), p=dist)
            prediction = self.model.config.decoder.chars[idx]
            nodes += [prediction]
            if check_call:  # exception caught in main
                assert prediction not in ['DBranch', 'DExcept', 'DLoop', 'DSubTree']
            if prediction == 'STOP':
                edges += [SIBLING_EDGE]
                break
            js = self.generate_ast(psi, depth + 1, nodes, edges + [CHILD_EDGE])
            ast.append(js)
            edges += [SIBLING_EDGE]
            num += 1
        return ast, nodes, edges

    def generate_ast(self, psi, depth=0, in_nodes=['DSubTree'], in_edges=[CHILD_EDGE]):
        assert depth < MAX_AST_DEPTH
        ast = collections.OrderedDict()
        node = in_nodes[-1]

        # Return the "AST" if the node is an API call
        if node not in ['DBranch', 'DExcept', 'DLoop', 'DSubTree']:
            ast['node'] = 'DAPICall'
            ast['_call'] = node
            self.calls_in_last_ast.append(node)
            return ast

        ast['node'] = node
        nodes, edges = in_nodes[:], in_edges[:]
```

**Comment by jajajaqlt** [comment]
I think when we resolve this issue, we can merge this into the master since I made some modifications in this branch to address this bug.

**Comment by vijay-murali** [comment]
You're right that in principle, any word in the vocabulary can be output by the decoder as we're sampling after all. However, if the model was trained right, it shouldn't happen that often because C0 will get an extremely low probability. Maybe it was a bad sample.

In any case, we need to resolve this. Can you investigate the code to see if we actually use C0 anywhere? In an extremely old version of the system we used it to indicate end of path, but I don't think we do that anymore.

**Comment by jajajaqlt** [comment]
After looking at the code, we're now basically only using C0 to fill the vocabulary in the config.json. The bug really happens with low probability. It happens once for a validation file of 10,000 programs with ~5 out_asts each. So, it's 0.002%. But it still happens with a large file. Now, we use **STOP** instead of **CLASS0** for ending.

**Comment by vijay-murali** [comment]
Alright, so the right way to fix this would be to get rid of C0 from the code. Can you do that and update the PR? Of course, keep your current fix (with the check) for compatibility with already trained models.

**Comment by jajajaqlt** [comment]
Sure. What is the PR?

**Comment by vijay-murali** [comment]
PR = Pull Request (I should have mentioned this, sorry). Open one when the C0 bug has been fixed in your branch, and we can merge it with master.

**Comment by vijay-murali** [comment]
@jajajaqlt, if you have not encountered this issue again can you go ahead and close this? If I remember this was because of another issue with training/testing on datasets with different vocabularies.
