### ISSUE TITLE
Which python script is to get the metrics defined in your paper?

### ISSUE THREAD

**Issue by shelfee** [capergroup/bayou#116]
The paper intruduced M1, M2, M3, M4 to evaluate the performance of BED. When we have trained BED model, how to run scripts to get these metrics?  

And in "bayou/src/main/python/bayou/experiments/predict_asts/tree_edit.py", I fail to import zss and editdistance. In "bayou/src/main/python/experimental/lda/data_reader.py ", I fail to import dsl. Where can I find these packages?

**Comment by vijay-murali** [comment]
The metrics in the paper are computed using the predict_asts package:
https://github.com/capergroup/bayou/tree/master/src/main/java/edu/rice/cs/caper/bayou/application/experiments/predict_asts

tree_edit.py is outdated. Generally, the experiment folders are not guaranteed to be compatible with the current Bayou version, as mentioned in the README under the folder. If you wish to run LDA, refer to the module bayou.lda that is actively maintained:
https://github.com/capergroup/bayou/tree/master/src/main/python/bayou/lda

**Comment by vijay-murali** [comment]
Closing this. Feel free to re-open if you have further questions.
