### ISSUE TITLE
Floodgage requires a timeout

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#128]
Occasionally a synthesized program can have an infinite loop or a blocking call. When floodgage runs the program it gets stuck. A timeout (say 30s) for each test should prevent this. Preferably the timeout should be configurable when running floodgage.

**Comment by rmbarnett-rice** [comment]
Under construction.

**Comment by rmbarnett-rice** [comment]
Actually, the cleanest way to address this may be at the juinit layer.  Do you have a trialpack that does this often I could play with?

**Comment by rmbarnett-rice** [comment]
Yes, this looks promising and clean. Consider replacing @Test in your TestSuite.java with @Test(timeout = 10000) // 10 second timeout

**Comment by vijay-murali** [comment]
Okay, that sounds good.
