### ISSUE TITLE
Bayou synthesizes unexpected non-JDK code (annotations.Bayou)

### ISSUE THREAD

**Issue by cogumbreiro** [capergroup/bayou#140]
I am unsure if this is problematic, so here it goes anyway.

Here is the command I ran:
```
tool_files/floodgage$ ./floodgage.sh trials/create_file/trials.jar $BAYOU
```

And here is the suspicious output:
```
[Synthesis Result 8]

	import java.io.*;
	import java.util.function.*;
	import java.io.File;
	import edu.rice.cs.caper.bayou.annotations.Bayou;
	import java.net.URI;
	
	public class Draft_1_8 implements Consumer<String> {
	
	  public void accept(String filename) {
	
	    {
	      boolean boolean1;
	      File file1;
	      long long1 = (long) Bayou.$init();
	      URI uRI1 = (URI) Bayou.$init();
	      file1 = new java.io.File(uRI1);
	      boolean1 = file1.setLastModified(long1);
	    }
	  }
	}
/Draft_1_8.java:4: error: package edu.rice.cs.caper.bayou.annotations does not exist
import edu.rice.cs.caper.bayou.annotations.Bayou;
```

**Comment by vijay-murali** [comment]
Use of the Bayou.$init method call is expected in some outputs, when the "environment" (the variables you provide as inputs) are not sufficient to synthesize a program from the model. For example, this particular program needed a long and an URI argument, so it calls the stub method Bayou.$init. The error you see is the result of a CLASSPATH issue, which can be fixed easily.

@rmbarnett-rice, are we ready to import the floodgage changes to the trials branch? If so, can you fix this before starting a pull request?

**Comment by cogumbreiro** [comment]
I understand, so $init is a place holder, which means that any sketch with placeholders are known to be incomplete. Why are incomplete sketches in the returned values? Is it for debugging?

**Comment by vijay-murali** [comment]
Yes, debugging and also feedback. End users who are unfamiliar with an API may not know what exactly are the inputs to provide to work with the API. When they see such partial programs, it gives them feedback about the types that are often used in that API. In the web interface we will be replacing the $init call with a meaningful comment (e.g., ```/* initialize this variable */```).

**Comment by cogumbreiro** [comment]
Great. So, in short, the only bug here is this:
```
/Foo_2_6.java:3: error: package edu.rice.cs.caper.bayou.annotations does not exist
import edu.rice.cs.caper.bayou.annotations.Bayou;
```

**Comment by vijay-murali** [comment]
Yes, actually, let's leave the issue open till the bug (i.e., the compilation error) is addressed.

**Comment by rmbarnett-rice** [comment]
So, to be clear, you are asking edu.rice.cs.caper.bayou.annotations.Bayou to be available during floodgage compilation?

**Comment by vijay-murali** [comment]
Yes, and also set CLASSPATH when running floodgage.sh to include Bayou.class.

**Comment by rmbarnett-rice** [comment]
Looks like if you take latest of trials branch and recompile floodgage you should pick up the needed changes:

```
/bayou/trials/tool_files/maven_3_3_9/floodgage$ mvn package
```

take the

```
target/floodgage-1.0.0-jar-with-dependencies.jar
```
as the new jar.

**Comment by cogumbreiro** [comment]
I'm unsure what I'm doing wrong, but I'm getting this error when running `mvn package`:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project floodgage: Compilation failure
[ERROR] /home/tiago/Work/bayou/src/main/java/edu/rice/cs/caper/bayou/core/synthesizer/Visitor.java:[18,43] package edu.rice.cs.caper.bayou.annotations does not exist
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by capergroup** [comment]
Are you sure you are on the trials branch and up to date?  I have the file at:

```
$ ls trials/src/main/java/edu/rice/cs/caper/bayou/annotations/Bayou.java 
trials/src/main/java/edu/rice/cs/caper/bayou/annotations/Bayou.java
```

**Comment by cogumbreiro** [comment]
Yes, I am on the latest branch and I do not have that file.
```
$ git log | head -n1
commit 89af9e8810b34cd2d370268be1abea90e8a8bbcb
$ git branch
  master
* trials
$ ls trials/src/main/java/edu/rice/cs/caper/bayou/annotations/Bayou.java 
ls: cannot access 'trials/src/main/java/edu/rice/cs/caper/bayou/annotations/Bayou.java': No such file or directory
$ git pull
Already up-to-date.
```

**Comment by vijay-murali** [comment]
@rmbarnett-rice, looks like we have to merge the changes to master into the trials branch. There were a few other changes to floodgage in master. Are we ready to bring them into trials?

**Comment by rmbarnett-rice** [comment]
Yea, I guess I have a local rebase that I haven't pushed.  I think catching trails up to master is ok.

**Comment by vijay-murali** [comment]
Okay, issue a pull request from master->trials once your local changes have been pushed.

**Comment by vijay-murali** [comment]
@cogumbreiro, we have merged the latest changes from master into trials. The "package does not exist" error should have been fixed. Can you confirm this, and close the issue if so?

**Comment by cogumbreiro** [comment]
@vijay-murali, it appears that I'm now missing file  `floodgage-1.0.0.jar` on the branch trials, so I am unable to run floodgage. Did this process change?

**Comment by cogumbreiro** [comment]
By the way, I'm looking at commit 70a469a694121a3e848b60f87c9c03d71d5d9782, where file `floodgage-1.0.0.jar` is missing. This also means that I am unable to test _any_ trial at this point.

**Comment by vijay-murali** [comment]
The new updates from master had changed the build process for floodgage. @rmbarnett-rice, can you check this?

**Comment by vijay-murali** [comment]
Is this issue cleared? Are the test engineers able to proceed?

**Comment by cogumbreiro** [comment]
@vijay-murali The file is still missing at  4579319c396e6, so at this point I am stalled. Maybe there is some new way of building `floodgage-1.0.0.jar` that I'm missing?

**Comment by vijay-murali** [comment]
@rmbarnett-rice, can you take a look at this issue? The test engineers need to be unblocked.

**Comment by rmbarnett-rice** [comment]
Did performing these steps not work?

    https://github.com/capergroup/bayou/issues/140#issuecomment-351200695

**Comment by cogumbreiro** [comment]
@rmbarnett-rice, I missed that one. I can confirm that it does work. I've added a safeguard in `floodgage.sh` that automatically compiles the JAR when that is missing.

**Comment by rmbarnett-rice** [comment]
Cool. Can we close the issue?

**Comment by rmbarnett-rice** [comment]
Bumping. Can we close this issue?
