### ISSUE TITLE
Draft silences/breaks Bayou 

### ISSUE THREAD

**Issue by cogumbreiro** [capergroup/bayou#141]
The following code snippet silences Bayou. I've tried using the web UI and got the same (silent) output.
```
	import java.io.*;
	import java.util.function.*;
	
	public class Draft implements BiConsumer<String, String> {
	
	    public void accept(String filename1, String filename2) {
	        
	{/// copy file
	/// type: Files
	/// call: copy
	}
	    }
	
	}
```

The code is checked in as well. To reproduce it try:
```
tool_files/floodgage$ ./floodgage.sh trials/copy_file/trials.jar 34.234.72.252
```

**Comment by vijay-murali** [comment]
@cogumbreiro, it looks like the currently trained model/corpus does not utilize the Files API often. There are only a handful of instances of that API. One reason could be that the corpus is old (it's from 2011), which is about the same time this API was released.

However, *this is a totally valid trial*. The corpus or model should not limit you in designing trials. I would suggest you go ahead and check this in once you are confident that your PassProgram is correct. Trials such as this one are really useful for us in evaluating how to expand Bayou further.

**Comment by cogumbreiro** [comment]
Great to know! Actually in this particular package there are 2 trials, one using an older API and one using the Java 7 API. Thanks for the insight.

Should we leave the bug open?

**Comment by vijay-murali** [comment]
Glad to help! Let's close the issue, as this will be tracked by the trial anyway.
