### ISSUE TITLE
About running Bayou

### ISSUE THREAD

**Issue by zhuzhujulie** [capergroup/bayou#147]
Hi dear anthor,
     How can i run Bayou under the os of windows10?
    Cause i install tensorflow on windows system~~

**Comment by rmbarnett-rice** [comment]
Running on Windows 10 is not directly supported at this time; however, I might suggest running the system on Windows 10 via the Windows Linux Subsystem: https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

**Comment by vijay-murali** [comment]
Closing the thread. Reopen if you have further questions/issues.
