### ISSUE TITLE
About running

### ISSUE THREAD

**Issue by zhuzhujulie** [capergroup/bayou#154]
Hi dear author， when i finished the compiling step. I try to run the order of "synthesize.sh", but i get the error information "HttpConnectException: connect to localhost:8080   ....failed, connection refused".
Do you know why?

**Comment by vijay-murali** [comment]
Did you run start_bayou.sh after building?

**Comment by zhuzhujulie** [comment]
Dear author,
I run it again this morning.
from the first step,
but when i run the order of "sudo ./install_dependencies", it seems that something got wrong.
below is the error messages:
      Downloading/unpacking tensorflow==1.4
      Could not find any downloads that satisfy the requirement tensorflow==1.4
do you know why, cause i have installed tensorflow1.4 on my linux virtual machine.

**Comment by vijay-murali** [comment]
Do you have Python 3? If so, try running this command and then the install script:
```
sudo pip3 install --upgrade pip
```

**Comment by zhuzhujulie** [comment]
Even though i got some wrong tips in the step of install_dependencies.sh ，but it works when i run the tools after building.
