### ISSUE TITLE
About the Code

### ISSUE THREAD

**Issue by zhuzhujulie** [capergroup/bayou#155]
Can you tell me how to run your tool from the source code(using an IDE) rather than the step you provided.
Cause i find it difficulty to understand the structure of the code. It is complex~

**Comment by vijay-murali** [comment]
If you want to explore and modify the source code, you can open the project `tool_files/intellij_2017/bayou` with IntelliJ and `tool_files/py_charm_2017` with PyCharm. You can then run the pre-defined automated tests from the IDE. To run Bayou end-to-end with a trained model, however, you have to use the command line, as we have not configured it to work with an IDE. Follow the instructions in the main README.

**Comment by zhuzhujulie** [comment]
Thank you so much, i'll have a try.

**Comment by vijay-murali** [comment]
Closing the thread. Reopen if you have further questions/issues.
