### ISSUE TITLE
-Xbootclasspath/p is no longer a supported option

### ISSUE THREAD

**Issue by rmbarnett-rice** [capergroup/bayou#165]
Using start_bayou.sh to launch the Java Bayou process no longer operates due to "-Xbootclasspath/p is no longer a supported option" error.

**Comment by rmbarnett-rice** [comment]
What is the role of rt_debug.jar?

**Comment by vijay-murali** [comment]
rt_debug.jar is going to be the JVM for running Bayou. I've compiled it with debug symbols which Bayou is going to use for a new "smart variable" system. I don't get this error when booting though. What version of Java are you running?

**Comment by rmbarnett-rice** [comment]
1.9.  What does it mean for a jar file to be a JVM? I don't understand that.

**Comment by vijay-murali** [comment]
It contains the Java runtime environment classes compiled with debug symbols (which is not usually done in the rt.jar supplied with JRE). I tried booting with the normal JVM and then loading these classes dynamically but the JVM doesn't allow loading of java.* classes as you would normally any other class. So the other option was to modify -Xbootclasspath/p when the JVM is started.

As for this error, have you tried running with Java 8?

**Comment by rmbarnett-rice** [comment]
Looks ok in 1.8.  Do we want to say 1.8 is the only supported version?

**Comment by vijay-murali** [comment]
Yes, let's do that for now. This option has been removed in 1.9 but the effect can be achieved with other options. I'm looking into that.
