### ISSUE TITLE
How do you extract sketch from a program?

### ISSUE THREAD

**Issue by ljy296566** [capergroup/bayou#169]

**Comment by ljy296566** [comment]
The directory `bayou-master\src\main\java\edu\rice\cs\caper\bayou\application\experiments\low_level_sketches` seems to be used to extract the sketch, but how to use it?

**Comment by vijay-murali** [comment]
To extract sketches from Java programs use the DOM driver system of Bayou. The source is here:
https://github.com/capergroup/bayou/tree/master/src/main/java/edu/rice/cs/caper/bayou/core/dom_driver, and you can compile/run it here: https://github.com/capergroup/bayou/tree/master/tool_files/maven_3_3_9/dom_driver.

**Comment by vijay-murali** [comment]
Closing the thread. Reopen if you have further questions/issues.
