### ISSUE TITLE
Remove max_ast_count parameter from AST server

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#179]
Can we get rid of this parameter from the AST server?
https://github.com/capergroup/bayou/blob/master/src/main/python/bayou/server/ast_server.py#L64

Here's why I think we shouldn't use it. Often times, an AST will not be able to be synthesized into a program, for various reasons. In these cases, we should pick the next AST and work on it. However, if we are filtering ASTs from the server itself, we won't have access to them all. Therefore I think this filtering should be done elsewhere (e.g., in the synthesizer) and not the AST server. The AST server should just return all ASTs that were computed.

**Comment by rmbarnett-rice** [comment]
This seems reasonable to me.  I'll implement this.

**Comment by rmbarnett-rice** [comment]
Merge to master.
