### ISSUE TITLE
Current master codebase incompatable with current master model configuration.

### ISSUE THREAD

**Issue by rmbarnett-rice** [capergroup/bayou#185]
When starting Bayou:

```
Traceback (most recent call last):
  File "/home/barnett/bayou/master/tool_files/build_scripts/out/python/bayou/server/ast_server.py", line 166, in <module>
    bp = model(args.save_dir, sess)  # create a predictor that can generates ASTs from evidence
  File "/home/barnett/bayou/master/tool_files/build_scripts/out/python/bayou/models/low_level_evidences/infer.py", line 54, in __init__
    with open(os.path.join(save, 'callmap.pkl'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/barnett/bayou/master/tool_files/build_scripts/out/resources/model/callmap.pkl'
```

Master model is currently 39-38. Does it need to catch up to the codebase? If so please provide a link to new master model and I will update.

**Comment by rmbarnett-rice** [comment]
Current master is 0f8a95c12c71c4704dde19e151396b622e2a84f0

**Comment by vijay-murali** [comment]
Yes, actually, I wanted to update you on this. One of yesterday's commits makes the old model incompatible. In any case, we need to update to the new model as 39.38 is quite outdated. I've sent you an email with the new model path.
