### ISSUE TITLE
Unable to run dom_driver due to log4j issue

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#192]
@jajajaqlt sent me an email with the following issue:

I set config.json to:
{
  "api-modules": [
      "java",
      "javax"
  ]
}

program.txt to:
// Bayou confidence score: 0.01513
import java.util.*;

public class Test {
  void foo(List<String> l, String s) {
    boolean b4;
    boolean b2;
    boolean b5;
    boolean b3;
    boolean b1;
    b1 = l.add(s);
    b2 = l.add(s);
    b3 = l.add(s);
    b4 = l.add(s);
    b5 = l.add(s);
    return;
  }
}

and run:
java -jar dom_driver-1.0-jar-with-dependencies.jar -f program.txt -c config.json -o output.txt

and got:
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.

**Comment by jajajaqlt** [comment]
Thanks Vijay for creation of the issue. :)

**Comment by rmbarnett-rice** [comment]
This message will not prevent execution from continuing. It is just a warning message that no log4j config file was set during startup. It can safely be ignored if you don't care about preserving any of the system's log messages. Otherwise invoke with the extra parameter

```
-DconfigurationFile=[BAYOU_HOME]/resources/conf/apiSynthesisServerConfig.properties
```

**Comment by jajajaqlt** [comment]
@rmbarnett-rice thanks! 
When I ran this:
```
java -jar dom_driver-1.0-jar-with-dependencies.jar -f program.txt -c config.json -o output.txt
```
I didn't get any output. Contents of my files are in Vijay's message. I didn't see instructions on the formats of the files. Did I do things correctly?

**Comment by rmbarnett-rice** [comment]
@vijay-murali Is this the expected behavior?

**Comment by vijay-murali** [comment]
Sorry for the late reply, folks. @rmbarnett-rice, thanks for the input.

@jajajaqlt, there is no output because the DOM driver only extracts data from public methods. This is because only public methods are meant to be used by API clients. Sorry that I didn't notice this in the input before. Change the method signature to `public` and it works.

**Comment by jajajaqlt** [comment]
@vijay-murali thanks! It works. The ankle brackets are written with unicodes. This is expected, right?

**Comment by vijay-murali** [comment]
Yes, that's expected. I'm closing this issue since you mention that it works.

**Comment by jajajaqlt** [comment]
@vijay-murali @rmbarnett-rice thank you both!!!
