### ISSUE TITLE
Can no longer synthesize from "/// read a line"

### ISSUE THREAD

**Issue by mfagan451** [capergroup/bayou#193]
The input file below used to be a valid acceptance test:
```
public class TestIO 
{
	void read(String file) 
	{
		{
		/// read a line
		}
	}
}
```
Now,  this input synthesizes nothing.

Is this an expected change ??

**Comment by vijay-murali** [comment]
Yes, with model-50 this is no longer supported. Specifically, test cases should have `/// call:` or `/// type:` when specifying evidences.

**Comment by rmbarnett-rice** [comment]
We will update the acceptance test in branch 190.

**Comment by vijay-murali** [comment]
Closing the issue as this is expected behavior.
