### ISSUE TITLE
Authors comments on adaptation for Python idoms

### ISSUE THREAD

**Issue by nkeilar** [capergroup/bayou#204]
Sorry this is not an issue, feel free to remove if you feel its not appropriate. I'm interested in knowing what would be required to adapt the research to support python idoms? Have the authors got any comments on that, or explored that previously?

**Comment by vijay-murali** [comment]
While we haven't explored Python idioms ourselves, we believe the technology is very much applicable there too. The statistical model of Bayou is actually agnostic to the programming language - it sees everything as words in a vocabulary, so it doesn't need to change too much. The [PL part](https://github.com/capergroup/bayou/tree/master/src/main/java/edu/rice/cs/caper/bayou/core), of course, needs to change. Specifically, the DOM driver that extracts data, the DSL of sketches, and the synthesizer.

**Comment by vijay-murali** [comment]
Closing this issue now. Feel free to re-open if you have further questions.
