### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by ejoebstl** [capergroup/bayou#205]
Thank you for putting a demo online and sharing the source code. 

I would be nice to have more examples though. At the moment, most examples seem to be file centered, but what about simpler operations? How would I, for example, express:

* Summing up two lists, element wise? 
* Removing a certain element from a list? 
* Simply add two integers? 
* Compare if two integers are equal? 

Maybe I'm not doing it right, but 

```
public class Test {
    boolean isSame(Integer a, Integer b) {
        {
            /// call:equals    
        }
    }
}
```

yields

```
public class Test {
  boolean isSame(Integer a, Integer b) {
    {
      int i1;
      boolean b1;
      String s1;
      i1 = (s1 = String.valueOf(a)).length();
      b1 = s1.equals(a);
      return b1;
    }
  }
}

```

**Comment by vijay-murali** [comment]
Many thanks for your feedback. We will add more examples of usage to the website.

Generally, the current version of Bayou is more suited to handling tasks which involve API method calls. Tasks such as adding integers or lists of integers or checking for equality of integers typically might not involve API calls (people would use operators such as + and ==), so those patterns may not be captured well by Bayou. On the other hand, removing an element at some index from a list does involve API calls, which Bayou can capture:

```
import java.util.*;
public class TestList {
    void remove(List<String> list, int index) {
        {
            /// call:remove
        }
    }
}
```

One of the top-5 programs is:
```
import java.util.*;
import java.util.List;
import java.util.ArrayList;

public class TestList {
  void remove(List<String> list, int index) {
    {
      String s1;
      s1 = list.remove(index);
      return;
    }
  }
}
```

We will update the documentation to inform users better as to what can be expected from the current system.

**Comment by vijay-murali** [comment]
Closing this issue now. Feel free to re-open if you have further questions.
