### ISSUE TITLE
Training your own model

### ISSUE THREAD

**Issue by nayname** [capergroup/bayou#208]
As I can see, the model is downloaded from some remote server. Can I train my own model from a dataset (containing Java programs, I suppose?). Can you provide some instructions?

**Comment by zhangxii** [comment]
The batch DOM driver module could not be used to generate the sketches.
When I calling the target/batch_dom_driver-1.0-jar-with-dependencies.jar package, it prints out the first line of file.txt, and there's no movement left. But I can call the DOM driver module to generate sktech. 
In addition, I have two questions:
1. The config.json of batch module could refer to DOM driver module. So, should I add as much API -packages and API -classes to config of batch module as possible?
2. When the module does not respond, I wonder if there is something wrong with the format of my file.txt. The first line of my file.txt is: `/home/zyt/workspace/bayouData/java_file/DisjointSet.java`
