### ISSUE TITLE
Expanding to other languages

### ISSUE THREAD

**Issue by tanmayb123** [capergroup/bayou#213]
I love this project - the technology is really exceptional. I haven't been able to delve deep into the structure of the code yet, so quick question: If I wanted to contribute to this project and expand it to Swift, how would I go about doing that?

Thanks!

**Comment by vijay-murali** [comment]
Sorry about the (really) late reply. https://github.com/capergroup/bayou/issues/204#issuecomment-385322685 explains at a high level which parts of the system should be modified to support other languages. You can look at https://github.com/capergroup/bayou/issues/208 for a more detailed explanation of how to train your own model on a dataset.

Feel free to expand on any specific questions you may have.

**Comment by tanmayb123** [comment]
Thanks for getting back to me. I'll take a look shortly.
