### ISSUE TITLE
Bad error message for draft with multiple holes

### ISSUE THREAD

**Issue by swaratchaudhuri** [capergroup/bayou#24]
Here is some code I entered in Askbayou:

import edu.rice.cs.caper.bayou.annotations.Evidence;

```
public class TestIO1 {
    void read(String file) {
        Evidence.apicalls("readLine");
    }     
    void foo(String file) {
        Evidence.apicalls("readLine");
    }  
}
```

This leads to the message "Unexpected error. Please retry."

In general, Bayou should allow multiple holes in the draft. This could be a reasonable goal for version 1.2.0. However, at the very Instead, Bayou should return a message that clarifies that we currently only allow one hole in the code at one time, and Askbayou should deliver this message.

**Comment by vijay-murali** [comment]
Bayou currently returns a proper error message when multiple holes are provided in the draft. Let's handle this issue at capergroup/askbayou#21.
