### ISSUE TITLE
Incorrect handling of mixes of evidence declarations and normal statements.

### ISSUE THREAD

**Issue by swaratchaudhuri** [capergroup/bayou#25]
Here is some code I entered:

```
import edu.rice.cs.caper.bayou.annotations.Evidence;

public class TestIO1 {

    // Read from a file
    void read(String file) {
        Evidence.apicalls("readLine");
        System.out.println("moo moo.");
    }   
}
```
In the output, the System.out.println statement got eaten. That is, Bayou returned programs like:

```
import edu.rice.cs.caper.bayou.annotations.Evidence;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.InputStream;

public class TestIO1 {
    // Read from a file
    void read(String file) {
		String s;
		BufferedReader br;
		InputStreamReader isr;
		InputStream is;
		try {
			isr = new InputStreamReader((is = file.getClass().getResourceAsStream(file)));
			br = new BufferedReader(isr);
			while ((s = br.readLine()) != null) {
			}
		} catch (IOException _e) {
		}
	}   
}
```
In fact, the same thing happens when we change one of the demo examples slightly:

```
import edu.rice.cs.caper.bayou.annotations.Evidence;
import android.bluetooth.BluetoothAdapter;

public class TestBluetooth {
    /* Get an input stream that can be used to read from
     * the given blueooth hardware address */
    void readFromBluetooth(BluetoothAdapter adapter) {
        String address = "00:43:A8:23:10:F0";
        Evidence.apicalls("getInputStream");
        Evidence.types("BluetoothSocket");
    }   

}
```
All I have done here is removed the braces from the evidence declarations. This erases the definition of "address". We get:

```
import edu.rice.cs.caper.bayou.annotations.Evidence;
import android.bluetooth.BluetoothAdapter;
import java.io.IOException;
import java.util.UUID;
import android.bluetooth.BluetoothSocket;
import java.io.OutputStream;
import java.io.InputStream;

public class TestBluetooth {

    /* Get an input stream that can be used to read from
     * the given blueooth hardware address */
    void readFromBluetooth(BluetoothAdapter adapter) {
		OutputStream os;
		InputStream is;
		BluetoothSocket bs;
		try {
			is = (bs = adapter.getRemoteDevice(address).createInsecureRfcommSocketToServiceRecord(UUID.randomUUID()))
					.getInputStream();
			os = bs.getOutputStream();
		} catch (IOException _e) {
		}
	}   
}
```

**Comment by vijay-murali** [comment]
Jisheng (@jz10) had implemented it such that the set of Evidence.* calls should appear in a block, and the entire block is replaced with the synthesized code. This is so that we can distinguish one set of calls from another.

Going forward, if we want to allow for multiple queries in the same program, we have to make this clear in the tutorial.

**Comment by vijay-murali** [comment]
@jz10, can you look into this? [EvidenceExtractor](https://github.com/capergroup/bayou/blob/master/src/main/java/edu/rice/cs/caper/bayou/core/synthesizer/EvidenceExtractor.java#L94) does seem to catch this case and throw an exception. How is the code being synthesized still?

**Comment by jz10** [comment]
What's error msg do you want to throw?

**Comment by swaratchaudhuri** [comment]
I will clarify this in the tutorial. 

@jz10 I think it makes sense to report that evidence declarations have to be nested within a block.

**Comment by jz10** [comment]
Should I commit the fix into master?

**Comment by rmbarnett-rice** [comment]
No, if this is a bugfix against 1.0.0 then it should got into the 1_0_x branch.

**Comment by vijay-murali** [comment]
@jz10, has this been fixed and committed?

**Comment by jz10** [comment]
not yet, since the master branch  was frozen.

**Comment by vijay-murali** [comment]
As Matt mentioned, this should go into the 1_0_x branch, not master.

**Comment by jz10** [comment]
Committed to 1_0_x.

**Comment by vijay-murali** [comment]
Thanks, it works well! Closing the issue now.
