### ISSUE TITLE
Handle exceptions better

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#33]
Currently, Bayou throws a lot of unchecked exceptions during synthesis (this is because of the restriction of Eclipse's visitor API that does not allow its clients to throw exceptions). We need to handle this more systematically by declaring/using our own exception mechanisms.

**Comment by rmbarnett-rice** [comment]
I'm not against putting this in 1.1.0, but how are we deciding which features are targeted for 1.1.0?

**Comment by vijay-murali** [comment]
I think 1.0 is pretty much done, except for the performance improvements you are working on. We are targeting for a mid-August 1.1 release, so there's not much time anyway.

**Comment by vijay-murali** [comment]
Fixed in commit ca87165.

**Comment by vijay-murali** [comment]
By the way, if you can go over the commit and okay it from your end I'll merge it with master.
