### ISSUE TITLE
Allow user to change parameters per-query

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#35]
The user should be allowed to change (i) the number of samples, and (ii) the number of results to see, on a query-by-query basis.

**Comment by vijay-murali** [comment]
@rmbarnett-rice, check out c23f83e. ast_server has been modified to look for the key named "samples" in the JSON query and use the value if provided (default 100). What's left to do is to allow the user to specify this parameter either from the command line (when running synthesize.sh) or through the web interface, and pass that down to ast_server.

Can you take care of this? CLI is higher priority, by the way.

**Comment by rmbarnett-rice** [comment]
Yea, no problem.

**Comment by vijay-murali** [comment]
@rmbarnett-rice, I'm going to be merging branches into master soon. This issue seems to have been fixed in ed9f594. Can I close this thread?

**Comment by vijay-murali** [comment]
Are we completely done with 1_0_x? If so, I will begin the merge.

**Comment by rmbarnett-rice** [comment]
In my mind no.  I feel this is still an outstanding issue:

https://github.com/capergroup/bayou/issues/42

**Comment by vijay-murali** [comment]
Just fixed and closed it. Are we go on merging 1_0_x to master? We should not make any more changes to 1_0_x (even bug fixes), as it's quite behind master. All development should be towards the next release.

**Comment by rmbarnett-rice** [comment]
No bug fixes? I find that a shocking statement.

**Comment by rmbarnett-rice** [comment]
As for merging a release branch into master, recommend doing so once the release branch puts out a RC that passes release criteria.  Let me package up what we have into a new RC and run it through the tests.

**Comment by vijay-murali** [comment]
No bug fixes towards 1_0_x, which will be obsolete after the next release anyway. This is a research tool with a small dev team, so I think we should focus our resources accordingly. Merging 1_0_x with master is already going to be a pain.

**Comment by swaratchaudhuri** [comment]
I agree. Once the next release is out (within the next week to 10 days), we can assume 1.0.0 to be basically obsolete. We need to focus our resources on what matters.

-Swarat

--

**Comment by vijay-murali** [comment]
Fixed and brought into master in f971ba5. Deleting the issue-35 branch.
