### ISSUE TITLE
Integrate experiments code into testing suite

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#37]
The experiments infrastructure (particularly, predict_asts) can be used as a large scale testing suite on the testing data. Integrate this into the main codebase by cleaning up the code and automating the tasks required to perform the tests.

**Comment by vijay-murali** [comment]
@rmbarnett-rice, we need a publicly accessible place to store the testing data so that it can be downloaded when one runs this large test suite. The data is a few hundred MBs in size. Can you suggest where/how to store it?

**Comment by rmbarnett-rice** [comment]
GitHub lets us upload files larger than 100mb in association with a release. 

(See https://github.com/capergroup/bayou/releases/download/v1.0.0-RC3/bayou-1.0.0_RC3.zip)

So maybe there or on our DreamHost account.

**Comment by vijay-murali** [comment]
I had to move ast_server to a new Python module to implement this feature. Take a look at 305527b and let me know if you find it okay.

**Comment by rmbarnett-rice** [comment]
Your changes in db1ebd4 appear reasonable to me.

**Comment by rmbarnett-rice** [comment]
@vijay-murali lets try uploading the test data to our dreamhost account. Where is it currently?

**Comment by vijay-murali** [comment]
The test data is on sisyphus. Can you email me instructions on uploading it to Dreamhost? I will proceed with merging this branch.

**Comment by rmbarnett-rice** [comment]
Done.

**Comment by vijay-murali** [comment]
Pull request #49 merges this with master.
