### ISSUE TITLE
synthesize.sh messes up argument values

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#47]
Running Bayou at 24a905c.

`./synthesize.sh --num_programs 3 example_inputs/TestIO.java`

From logs/ast_server.log:
```
{
  "max ast count": 2147483647,
  "evidence": "{\n  \"apicalls\": [\n    \"readLine\"\n  ],\n  \"types\": [],\n  \"context\": []\n}",
  "sample count": 3
}
```

**Comment by rmbarnett-rice** [comment]
Can reproduce seeing incorrect JSON message in logs.  But strangely I see the command line respecting the number of programs displayed to the console.

**Comment by rmbarnett-rice** [comment]
Value incorrect by time reaches REST server.

**Comment by rmbarnett-rice** [comment]
Copy paste error. I suspect it passed testing because turning down the sample count may also have turned down the number of asts returned by python and thus the number of programs displayed to the user.
