### ISSUE TITLE
Duplicate scripts install_deps_* and install_dependencies_*

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#50]
Why are there two sets of scripts to install dependencies?

https://github.com/capergroup/bayou/tree/master/tool_files/build_scripts
https://github.com/capergroup/bayou/tree/master/src/main/bash/binary_release

We should just have one set that installs everything needed to build/run Bayou, and copy it wherever we want after packaging.

**Comment by rmbarnett-rice** [comment]
The first installs the deps you need to run ./build.sh in the same directory.  The second defines what the end user would need to install to run Bayou if they downloaded the binary release.

I disagree that we should just have one script to install all deps for either building or running Bayou.  The dependencies a dev needs to build are different than what an end user needs to simply run.  For example, if you are an end user that just downloads one of the release zip files (i.e. a binary release) you don't need to install Maven and you don't need the JDK (just JRE).  However, if you are a dev looking to run ./build.sh you do need to install both Maven and the JDK.

**Comment by rmbarnett-rice** [comment]
Though, I'm not sure that pip stuff needs to be there on second glance of the first file. I don't think the build system cares if that stuff is installed yet.  But the maven and jdk parts are required.

**Comment by vijay-murali** [comment]
In that case, there should be one script that accepts different command line arguments, such as install_deps.sh mac user, install_deps.sh linux dev, etc. I just upgraded the dep version for scikit-learn, and I had to update 4 different files (not to mention in different directories), which just doesn't make sense.

**Comment by rmbarnett-rice** [comment]
Can you point me to the commit where you had to change it in 4 places?  I'd like to identify the 4 places.

**Comment by vijay-murali** [comment]
3f64aed -- the 4 .sh files that I had to update.

**Comment by rmbarnett-rice** [comment]
I remember why those pip lines are there now.  Prior to having them there was an objection to a developer having to run `/binary_release/install_dependencies_apt.sh` and then `out/install_dependencies_apt.sh` to start the program.

As such, we might consider replacing the pip lines with

    apt-get update
    apt-get install openjdk-8-jdk maven
    ../../src/main/bash/binary_release/install_dependencies_apt.sh

**Comment by rmbarnett-rice** [comment]
Though, I still stand behind my claim that the script should be:

    apt-get update
    apt-get install openjdk-8-jdk maven

because that is all that is required to run `build.sh`

**Comment by vijay-murali** [comment]
How about we have a single script with a command line option? In any case, we shouldn't have four scripts with two for Mac/Linux each. As I mentioned, use `uname` to detect the OS which will return "Darwin" for Mac.

**Comment by rmbarnett-rice** [comment]
`uname` makes sense to me. I guess it's still a a little unclear to me what the command line switch is supposed to do.

**Comment by rmbarnett-rice** [comment]
I think this gives us a single point of control on the pip statements across all .sh files:

https://github.com/capergroup/bayou/commit/8afce343667be32f22014b7e9c6ea7d370ae135c

**Comment by vijay-murali** [comment]
Looks good. Can you also update README.md and start a pull request?

**Comment by rmbarnett-rice** [comment]
Done.

**Comment by vijay-murali** [comment]
Merged PR #55.

**Comment by vijay-murali** [comment]
@rmbarnett-rice, Do we need the issue-50 branch alive, given that this issue has been closed?

**Comment by rmbarnett-rice** [comment]
I see the issue is marked as awaiting merge, but also your comment that it was merged.  So I think we are ok to close the branch.
