### ISSUE TITLE
Why must evidence be specified within a seprate block?

### ISSUE THREAD

**Issue by rmbarnett-rice** [capergroup/bayou#56]
What is our motivation for this constraint?

**Comment by swaratchaudhuri** [comment]
This is just how Jisheng implemented it. Anyway, all of this is going away soon, as evidence is declared using comments.

**Comment by rmbarnett-rice** [comment]
But evidence being declared via comments is orthogonal to whether blocks are used. We could mix and match both options of block/evidence.  Should this constraint be continued forward?

**Comment by vijay-murali** [comment]
To directly answer your question, it is to differentiate multiple holes (in future). Without being in a separate block, we wouldn't know if
```
foo() {
  ...
  Evidence.apicalls("readLine");
  Evidence.types("BufferedReader");
  ...
}
```
the user provides a single hole with two pieces of evidence, or two holes next to each other with one evidence each. A block represents a hole implicitly, and all evidence in a block is considered together. With the new triple slash notation, we should consider all evidence in a line as being together.

**Comment by swaratchaudhuri** [comment]
I think we should allow multiple triple slash comments to be part of the same evidence declaration though. The evidence declarations needed for a task may not fit on a line. We could use the block syntax for this. This means

{
/// call:readLine
/// type:BufferedReader
}

should have the same semantics as 

/// call:readLine type:BufferedReader

An alternative is to use a C-style comment notation that can span multiple lines

/**
 call:readLine
type:BufferedReader
**/

I am okay with both options, although the C-style comment seems simpler. We can use the web interface to autocomplete the closing of the comment, so the user doesn't need more keystrokes.

**Comment by rmbarnett-rice** [comment]
Can evidence be interleaved with statements? If not, I propose that all contiguous /// be treated as a single hole **unless** enclosed by a block.  So:

    void foo() {
        /// I am in hole A
        /// I am in hole A
    } 

    void bar() {
        /// I am in hole B
        /// I am in hole B
       int i = 0;
        /// I am in hole C
        /// I am in hole C
    }

    void zebra() {
       /// I am in hole D
       { 
            /// I am in hole E
            /// I am in hole E
       }
   }

**Comment by vijay-murali** [comment]
This would not be very consistent if, say, I would like to define two holes one after another with single evidence each.

```
void foo() {
  /// I am in hole D
  {
    /// I am in hole E
  }
}
```
Even though E is defining the same kind of input as D (single hole, single evidence), it has to defined differently than D, otherwise it will be conflated with D.

Why not always just have a consistent representation within a block? It's literally just two extra characters for the user.

**Comment by rmbarnett-rice** [comment]
In my vision 

    void foo() {
        { /// I am in hole D }
        { /// I am in hold E }
    }

would still be legal.

I like the brief syntax for the same reason I like line comments.  We could have a world in C like languages where all comments were block

    void bar()
    {
        /* a line comment */
       /* also
          a comment */
    }

But since single line comments are the most frequent comments they get special simpler syntax.  So when I think about evidence holes I ask my self: what is going to be most frequent? (probably statement, single evidence hole, statement) and how can I make that as simple and easy to read as possible?

**Comment by swaratchaudhuri** [comment]
I like Matt's suggestion. Not requiring braces for the special case where there's only one hole is a win IMO.

**Comment by vijay-murali** [comment]
Alright then, let's go with that. As minor point, we should be careful about this:
```
void foo() {
    { /// I am in hole D }
    { /// I am in hold E }
}
```
The ending } would be parsed as part of the comment line.

**Comment by rmbarnett-rice** [comment]
Ha. Good catch.  Yea, we would need to have the close braces on a new line. I was just saving space in my post.

**Comment by vijay-murali** [comment]
I believe this has been answered, so I'm closing this. Feel free to reopen if you want to discuss further.
