### ISSUE TITLE
Keywords evidence does not work

### ISSUE THREAD

**Issue by swaratchaudhuri** [capergroup/bayou#88]
As of now, the keywords evidence is not working on beta.askbayou. The following query yields no result.

import edu.rice.cs.caper.bayou.annotations.Evidence;

public class TestIO {
    void read(String file) {
        {
            /// read a line
        }
    }

}

**Comment by rmbarnett-rice** [comment]
For reference, what specific input did you try?

**Comment by vijay-murali** [comment]
Fixed in ebf8495.
