### ISSUE TITLE
Add argument to change timeout in synthesize.sh

### ISSUE THREAD

**Issue by vijay-murali** [capergroup/bayou#93]
I'm getting timeouts when running synthesize.sh on some obscure APIs that may take longer to generate ASTs or synthesize. It would be useful to have a command line option to control this. Maybe -t or something.

**Comment by rmbarnett-rice** [comment]
I think we can do both, but just for reference are you aware you can change this setting for the whole server at:

https://github.com/capergroup/bayou/blob/c4a53506d677a25267d067ba664d9de932a9fdc0/src/main/resources/conf/apiSynthesisServerConfig.properties#L19

**Comment by vijay-murali** [comment]
Great! I can work with that till the command line option is added.
